markdown: kramdown
name: Code for DC
url: https://codefordc.org
title: Code for DC
description: "We are a non-partisan, non-political group of volunteer civic hackers working together to solve local issues and help people engage with the city."
encoding: utf-8
timezone: America/New_York
gems:
  - jekyll-redirect-from
future: true
baseurl: ''

collections:
  - projects
sass:
  sass_dir: _sass
  style: compressed
exclude: ['sass/bootstrap/docs','sass/bootstrap/docs/index.html', 'sass/bootstrap/index.html']
include: ['sass/bootstrap/scss']
