version: '2'
services:
    postgres:
        image: postgres
        # TODO: use environment variable for password
        environment:
            - POSTGRES_PASSWORD=ancfinder_pass
            - POSTGRES_USER=ancfinder
            - POSTGRES_DB=ancfinder
    # TODO: copy the static media into nginx from ancfinder
    nginx:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./uswgi_params:/home/docker/code/uwsgi_params
        ports:
            - "80:80"
        links: 
            - ancfinder
    ancfinder:
        image: codefordc2/ancfinder:releae
        links:
            - postgres
        volumes: 
            - ./environment.yaml:/home/ancfinder/environment.yaml
